services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: uofthub
      POSTGRES_PASSWORD: uofthub
      POSTGRES_DB: uofthub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
